---
- name: Install dependencies
  become: yes
  package:
    name:
      - xorriso
      - gpg
      - curl
    state: present
  when: ansible_distribution == "Ubuntu"
 - name: Install dependencies (archlinux)
  become: yes
  community.general.pacman:
    name: 
      - xorriso
      - gpg
      - curl
    state: present
  when: ansible_distribution != "Ubuntu" and ansible_os_family != "Darwin"

- name: Install dependencies (macOS)
  package:
    name:
      - xorriso
      - gnupg
      - curl
    state: present
  when: ansible_os_family == "Darwin"

- name: Create the temporary directory
  file:
    path: "{{ target_dir }}"
    state: directory
